[package]
name = "plonk_circuits"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
algebra-core = { path = "../../../zexe/algebra-core", features = [ "parallel"] }
ff-fft = { path = "../../../zexe/ff-fft", features = [ "parallel"] }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
array-init = { version = "0.1.1" }
rayon = { version = "1" }
blake2 = "0.7"

num-derive = "0.3"
num-traits = "0.2"
