[package]
name = "dlog"
version = "0.1.0"
edition = "2018"

[dependencies]
groupmap = { path = "../groupmap" }
mina-curves = { path = "../curves" }
commitment_dlog = { path = "commitment" }
plonk_circuits = { path = "../circuits/plonk" }
plonk_protocol_dlog = { path = "plonk" }
plonk_5_wires_circuits = { path = "../circuits/plonk-5-wires" }
plonk_5_wires_protocol_dlog = { path = "plonk-5-wires" }
oracle = { path = "../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = { version = "0.8.0", features = ["getrandom"] }
sprs = "0.7.1"
rayon = { version = "1" }

[dev-dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
