[package]
name = "dlog"
version = "0.1.0"
edition = "2018"

[dependencies]
algebra = { git = "https://github.com/o1-labs/zexe/", features = [ "parallel", "bn_382", "asm" ] }
groupmap = { git = "https://github.com/o1-labs/zexe/" }
ff-fft = { git = "https://github.com/o1-labs/zexe/" }
commitment_dlog = { path = "commitment" }
marlin_circuits = { path = "../circuits/marlin" }
marlin_protocol_dlog = { path = "marlin" }
plonk_circuits = { path = "../circuits/plonk" }
plonk_protocol_dlog = { path = "plonk" }
oracle = { path = "../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
rayon = { version = "1" }
