[package]
name = "dlog"
version = "0.1.0"
edition = "2018"

[dependencies]
algebra = { git = "https://github.com/o1-labs/zexe/", features = [ "parallel" ] }
groupmap = { git = "https://github.com/o1-labs/zexe/" }
ff-fft = { git = "https://github.com/o1-labs/zexe/" }
commitment_dlog = { path = "commitment" }
circuits_dlog = { path = "circuits" }
protocol_dlog = { path = "protocol" }
oracle = { path = "../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
rayon = { version = "1" }
