[package]
name = "commitment"
version = "0.1.0"
edition = "2018"

[dependencies]
oracle = { path = "../oracle" }
primes = "0.2.3"
rand = "0.4"
colored = "1.8"
rand_core = { version = "0.5" }

algebra = { git = "https://github.com/o1-labs/zexe/", features = [ "parallel" ] }
ff-fft = { git = "https://github.com/o1-labs/zexe/" }
