[package]
name = "marlin_circuits"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
algebra-core = { path = "../../../zexe/algebra-core", features = [ "parallel"] }
ff-fft = { path = "../../../zexe/ff-fft" }
