[package]
name = "oracle"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
mina-curves = { path = "../curves" }
ocaml = { version = "0.22.0", optional = true }
rand = "0.8.0"
rayon = { version = "1" }

# for export_test_vectors
num-bigint = { version = "0.3", optional = true }
custom_derive = { version = "0.1.7", optional = true }
enum_derive = { version = "0.1.7", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
hex = { version = "0.4", optional = true }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
hex = { version = "0.4" }
ark-serialize = "0.3.0"

[features]
ocaml_types = [ "ocaml" ]

# for test vectors
export_test_vectors = [ "serde", "serde_json", "hex", "num-bigint", "custom_derive", "enum_derive" ]
3w = [ ]
5w = [ ]
3 = [ ]

[[bin]]
name = "export_test_vectors"
test = false
bench = false
path = "tests/export_test_vectors/export_test_vectors.rs"
required-features = [ "export_test_vectors" ]
