[package]
name = "commitment_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
mina-curves = { path = "../../curves" }
groupmap = { path = "../../groupmap" }
ocaml = { version = "0.22.0", optional = true }
oracle = { path = "../../oracle" }
rand_core = { version = "0.6.0" }
colored = "1.9.2"
rand = "0.8.0"
rayon = { version = "1" }
blake2 = "0.7"
itertools = "0.8.2"
array-init = "0.1.1"

[features]

ocaml_types = [ "ocaml" ]
