[package]
name = "commitment_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
dlog_solver = { path = "../../dlog_solver" }
groupmap = { path = "../../../zexe/groupmap" }
ff-fft = { path = "../../../zexe/ff-fft", features = [ "parallel" ] }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
rayon = { version = "1" }
blake2 = "0.7"
itertools = "0.8.2"
