[package]
name = "commitment_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { git = "https://github.com/o1-labs/zexe/", features = [ "parallel" ] }
ff-fft = { git = "https://github.com/o1-labs/zexe/" }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
rayon = { version = "1" }
blake2 = "0.7"
itertools = "0.8.2"
