[workspace]

[package]
name = "marlin"
version = "0.1.0"

[dependencies]
array-init = { version = "= 0.1.1" }
blake2 = "0.8.1"
colored = "= 1.9.3"  # dlog/plonk
itertools = "= 0.8.2"
num-integer = "=0.1.43"
num-traits = { version = "= 0.2.11", default-features = false }
proc-macro2 = "= 1.0.17"
quote = "= 1.0.6"
rand = "= 0.7.3"
rand_core = "0.5"
rayon = "= 1.3.1"
sprs = "= 0.7.1"

# zexe
# num-bigint = { version = "= 0.2.3", features = ["i128"] }
# derivative = { version = "= 2.1.1", features = ["use_core"] }
# rustc_version = "= 0.2.3"
# syn = {version = "= 1.0.17", features = ["full"]}
# typenum = "= 1.12.0"
# unroll =  "= 0.1.4"

[features]
std = []

[lib]
# Mandatory (or Cargo tooling is unhappy)
path = "fake_lib.rs"

[raze]
genmode = "Remote"

# sets the repo names and load cmd to "marlin_fetch_remote_crates"
# gen_workspace_prefix = "marlin"

# The WORKSPACE relative path to the Cargo.toml working directory.
workspace_path = "//bzl/cargo"

# The target to generate BUILD rules for.
# target = "x86_64-unknown-linux-gnu"
target = "x86_64-apple-darwin"

# without this we get "Error: Is a directory (os error 21)"
output_buildfile_suffix = "BUILD.bazel"

[raze.crates.num-bigint.'0.2.3']
gen_buildrs = true
[raze.crates.crossbeam-epoch.'0.8.2']
gen_buildrs = true
[raze.crates.crossbeam-utils.'0.7.2']
gen_buildrs = true
[raze.crates.getrandom.'0.1.14']
gen_buildrs = true
[raze.crates.memoffset.'0.5.4']
gen_buildrs = true
[raze.crates.ndarray.'0.13.1']
gen_buildrs = true
[raze.crates.num-complex.'0.2.4']
gen_buildrs = true
[raze.crates.num-integer.'0.1.42']
gen_buildrs = true
[raze.crates.num-traits.'0.2.11']
gen_buildrs = true
[raze.crates.proc-macro2.'0.4.30']
gen_buildrs = true
[raze.crates.proc-macro2.'1.0.17']
gen_buildrs = true
[raze.crates.rayon-core.'1.3.1']
gen_buildrs = true
[raze.crates.syn.'0.15.44']
gen_buildrs = true
[raze.crates.syn.'1.0.17']
gen_buildrs = true
[raze.crates.typenum.'1.12.0']
gen_buildrs = true
# https://github.com/google/cargo-raze/issues/138
additional_flags = ["--cfg=feature=\\\"force_unix_path_separator\\\""]
[raze.crates.winapi.'0.3.8']
gen_buildrs = true
[raze.crates.winapi-i686-pc-windows-gnu.'0.4.0']
gen_buildrs = true
[raze.crates.winapi-x86_64-pc-windows-gnu.'0.4.0']
gen_buildrs = true

