[package]
name = "marlin_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
ff-fft = { path = "../../../zexe/ff-fft" }
commitment_dlog = { path = "../commitment" }
marlin_circuits = { path = "../../circuits/marlin" }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
rayon = "1.3.0"
