[package]
name = "protocol"
version = "0.1.0"
edition = "2018"

[dependencies]
algebra = { git = "https://github.com/scipr-lab/zexe/", features = [ "parallel" ] }
ff-fft = { git = "https://github.com/scipr-lab/zexe/" }
commitment = { path = "../commitment" }
circuits = { path = "../circuits" }
oracle = { path = "../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.0"
rand = "0.7.2"
sprs = "0.7.1"
